# golangci-lint v2 configuration for Nivo project
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - misspell

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (github.com/1mb-dev/nivomoney/shared/response).Error

    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    misspell:
      locale: US

    gosec:
      excludes:
        - G104
        - G307
        - G404

  exclusions:
    generated: lax
    paths:
      - vendor
      - node_modules
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec
          - errcheck

      - path: migrations/
        linters:
          - gocritic
          - gosec

      - path: services/simulation/
        text: "G404"
        linters:
          - gosec

      - path: .pb.go
        linters:
          - lll

      - path: shared/validator/validator\.go
        linters:
          - revive

      - text: "Error return value of `response.Error` is not checked"
        linters:
          - errcheck
      - text: "Error return value of `.*Encode` is not checked"
        linters:
          - errcheck

      # Type assertions used safely with known types from auth middleware
      - text: "Error return value is not checked"
        linters:
          - errcheck

      # "cancelled" is used in API/DB schema and user-facing strings - cannot change
      - text: "cancelled.*canceled"
        linters:
          - misspell

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
      colors: true
