# golangci-lint v2 configuration for Nivo project
version: 2

run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.22'

linters:
  # Use default linters + additional ones
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - gosec
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - (github.com/vnykmshr/nivo/shared/response).Error

  govet:
    enable-all: true
    disable:
      - shadow      # Too noisy for now

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      # Disabled package-comments and unused-parameter for now
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104  # Duplicates errcheck
      - G307  # Deferring unsafe method close

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - errcheck

    # Exclude migration files from some checks
    - path: migrations/
      linters:
        - gocritic
        - gosec

    # Allow long lines in generated code
    - path: .pb.go
      linters:
        - lll

    # Ignore errcheck for response.Error and json.Encode calls (they write directly to response)
    - text: "Error return value of `response.Error` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `.*Encode` is not checked"
      linters:
        - errcheck

    # Ignore package-comments and unused-parameter from revive for now
    - text: "package-comments:"
      linters:
        - revive
    - text: "unused-parameter:"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't report issues in vendor directories
  exclude-dirs:
    - vendor
    - node_modules

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
